{
 "title": "Playnite",
 "description": "Playnite gaming statistics",
 "tags": [
  "gaming",
  "playnite"
 ],
 "time": { "from": "now-30d", "to": "now" },
 "panels": [
  {
   "title": "Weekly play time",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "delta(playnite_game_playtime_seconds_total[1w])"
    }
   ]
  },
  {
   "title": "Played games",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "playnite_game_played_total" }
   ]
  },
  {
   "title": "Top played games",
   "type": "table",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "hours" } },
   "targets": [
    {
     "expr": "sort_desc(max(playnite_game_playtime_seconds) by (name))/3600"
    }
   ]
  },
  {
   "title": "Total game time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "playnite_game_playtime_seconds_total",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Daily game time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "delta(playnite_game_playtime_seconds_total[1d])",
     "legendFormat": "Daily"
    }
   ]
  },
  {
   "title": "Top played games of the week",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "hours" } },
   "targets": [
    {
     "expr": "sort_desc(max(increase(playnite_game_playtime_seconds[1w])) by (name))/3600 > 0"
    }
   ]
  }
 ]
}